-- Hanya database aplikasi DB_*. Tidak mengubah database SIMRS lama.
CREATE TABLE IF NOT EXISTS data_hais (
 no_rawat VARCHAR(17) NOT NULL,
 tanggal DATE NOT NULL,
 ETT INT NOT NULL DEFAULT 0,
 CVL INT NOT NULL DEFAULT 0,
 IVL INT NOT NULL DEFAULT 0,
 UC INT NOT NULL DEFAULT 0,
 VAP INT NOT NULL DEFAULT 0,
 IAD INT NOT NULL DEFAULT 0,
 PLEB INT NOT NULL DEFAULT 0,
 ISK INT NOT NULL DEFAULT 0,
 ILO INT NOT NULL DEFAULT 0,
 HAP INT NOT NULL DEFAULT 0,
 Tinea INT NOT NULL DEFAULT 0,
 Scabies INT NOT NULL DEFAULT 0,
 DEKU ENUM('IYA','TIDAK') NOT NULL DEFAULT 'TIDAK',
 SPUTUM VARCHAR(200) NOT NULL DEFAULT '',
 DARAH VARCHAR(200) NOT NULL DEFAULT '',
 URINE VARCHAR(200) NOT NULL DEFAULT '',
 ANTIBIOTIK VARCHAR(200) NOT NULL DEFAULT '',
 kd_kamar VARCHAR(15) NOT NULL,
 PRIMARY KEY (no_rawat,tanggal)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO sidebar_pasien (kode_sidebar,nama_sidebar,ikon,daftar_modul,urutan,aktif,created_at,updated_at)
SELECT 'data_hais','Data HAIs','ClipboardList',JSON_ARRAY('Rawat Inap'),65,TRUE,NOW(),NOW()
WHERE NOT EXISTS (SELECT 1 FROM sidebar_pasien WHERE kode_sidebar='data_hais');
